# Generated by Django 3.0.14 on 2021-09-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20210910_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='messages',
            new_name='message',
        ),
    ]
